### ISSUE TITLE
Not found agents

### ISSUE THREAD

**Issue by KanKai** [sanchezzzhak/node-device-detector#11]
- 'Mozilla/5.0 (Linux; Android 8.1; V11) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Mobile Safari/537.36',
- 'Mozilla/5.0 (Linux; Android 5.1; U2 Build/LMY47I; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/86.0.4240.198 Mobile Safari/537.36',
- 'Mozilla/5.0 (Linux; Android 8.1.0; W-K200 Build/O11019; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/86.0.4240.198 Mobile Safari/537.36'

**Comment by sanchezzzhak** [comment]
Hi.

the useragent 
`Mozilla/5.0 (Linux; Android 8.1.0; W-K200 Build/O11019; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/86.0.4240.198 Mobile Safari/537.36` added in version 1.3.1

Online test
https://iehol.sse.codesandbox.io/#Mozilla/5.0%20(Linux;%20Android%208.1.0;%20W-K200%20Build/O11019;%20wv)%20AppleWebKit/537.36%20(KHTML,%20like%20Gecko)%20Version/4.0%20Chrome/86.0.4240.198%20Mobile%20Safari/537.36

as for the other two agents. we can't add them to the definition, because the device ID contains too few characters. (minimum chars 4)
